### ISSUE TITLE
How to test it?

### ISSUE THREAD

**Issue by botsbuzz** [brianfajardo/turbo-octo-lamp#1]
Do I have to use Exponent? Could you write the url exp://... ?

Thank you for your effort on this,

Stefano

**Comment by brianfajardo** [comment]
Hi there,

On your mobile device, open up Expo and add/enter this project URL:
exp://exp.host/?brianfajardo/animation-gestures

Markdown won't let me add "@" infront of my name in the URL, so just replace the "?" with "@".

Let me know if I can help further,
Brian

**Comment by botsbuzz** [comment]
Great! Thank you!
